version: "3.9"

services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build: ./backend
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
